name = "JPEGs"
uuid = "2ab36f5f-bdf6-5943-bea2-9652ba9dca51"
authors = ["Matt Koski <maccam912@gmail.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
