[package]
name = "rsjpegs"
version = "0.1.0"
authors = ["Matt Koski <maccam912@gmail.com>"]
edition = "2018"

[lib]
name = "rsjpegs"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.1"
